SECURITY_DEPOSIT_APY: 20

#Solana RPC
SOLANA:
  RPC_URL: "http://127.0.0.1:8899"
  MAX_FEE_MICRO_LAMPORTS: 250000
  HELIUS_FEE_LEVEL: "veryHigh"

  STATIC_TIP: 100000

  MNEMONIC_FILE: "./wallet.txt"

STARKNET:
  RPC_URL: "http://127.0.0.1:5050/rpc/v0_8"

  MAX_L1_FEE_GWEI: 4000000
  MAX_L2_FEE_GWEI: 4000000
  MAX_L1_DATA_FEE_GWEI: 4000000

  CHAIN: "SEPOLIA"

  MNEMONIC_FILE: "./wallet.txt"
  AUTHORIZATION_TIMEOUT: 60

#Bitcoin RPC
BITCOIND:
  PROTOCOL: "http"
  PORT: 18332
  HOST: "127.0.0.1"
  RPC_USERNAME: "user"
  RPC_PASSWORD: "password"
  NETWORK: "regtest"

#LND RPC
LND:
  CERT_FILE: "~/.lnd/tls.cert"
  MACAROON_FILE: "~/.lnd/data/chain/bitcoin/regtest/admin.macaroon"
  HOST: "127.0.0.1"
  PORT: 20009
  MNEMONIC_FILE: "./wallet.txt"
  WALLET_PASSWORD_FILE: "./password.txt"

#LN setup
LN:
  BASE_FEE: 0.00000010
  FEE_PERCENTAGE: 0.3
  MIN: 0.00001000
  MAX: 0.01000000

  ALLOW_NON_PROBABLE_SWAPS: false
  ALLOW_LN_SHORT_EXPIRY: false

#On-chain setup
ONCHAIN:
  BASE_FEE: 0.00000150
  FEE_PERCENTAGE: 0.3
  MIN: 0.00010000
  MAX: 0.05000000

  NETWORK_FEE_ADD_PERCENTAGE: 25

  ADD_NETWORK_FEE: 5

ONCHAIN_SPV:
  MNEMONIC_FILE: "./wallet.txt"

  BASE_FEE: 0.00000150
  FEE_PERCENTAGE: 0.3
  MIN: 0.00003000
  MAX: 0.05000000

  GAS_MAX:
    STARKNET: 5
    SOLANA: 0.05

ASSETS:
  SOL:
    chains:
      SOLANA:
        address: "So11111111111111111111111111111111111111112"
        decimals: 9
        securityDepositAllowed: true
    pricing: "SOLBTC"
  ETH:
    chains:
      STARKNET:
        address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "ETHBTC"
  STRK:
    chains:
      STARKNET:
        address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "STRKBTC"

CLI:
  ADDRESS: "127.0.0.1"
  PORT: 40121

REST:
  ADDRESS: "0.0.0.0"
  PORT: 4001

RPC:
  ADDRESS: "127.0.0.1"
  PORT: 41121

SSL:
  CERT_FILE: "./server.cert"
  KEY_FILE: "./server.key"

#PLUGINS:
